# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.provision "shell", path: "install.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.gui = true
	vb.name = "GraPacc"
  end

end
